use DATABASE quiz;

-- =====================
-- Thématique : HTML
-- =====================
INSERT INTO Questions (thematique, question, options, correctAnswers) VALUES
('HTML', 'Que signifie HTML ?',
    JSON_ARRAY('HyperText Markup Language', 'Hyperlinks and Text Markup Language', 'Home Tool Markup Language'),
    'HyperText Markup Language'),
('HTML', 'Quel est l’élément racine d’un document HTML ?',
    JSON_ARRAY('<html>', '<head>', '<body>'),
    '<html>'),
('HTML', 'Quel tag est utilisé pour insérer une image ?',
    JSON_ARRAY('<img>', '<image>', '<pic>'),
    '<img>'),
('HTML', 'Quelle balise définit un lien hypertexte ?',
    JSON_ARRAY('<link>', '<a>', '<href>'),
    '<a>'),
('HTML', 'Quelle balise est utilisée pour les titres principaux ?',
    JSON_ARRAY('<title>', '<h1>', '<heading>'),
    '<h1>'),
('HTML', 'Quel attribut d’un lien définit l’URL de destination ?',
    JSON_ARRAY('src', 'href', 'link'),
    'href'),
('HTML', 'Quelle balise définit une liste ordonnée ?',
    JSON_ARRAY('<ul>', '<ol>', '<li>'),
    '<ol>'),
('HTML', 'Quelle balise est utilisée pour créer un tableau ?',
    JSON_ARRAY('<table>', '<tab>', '<grid>'),
    '<table>'),
('HTML', 'Quel attribut d’une image définit le texte alternatif ?',
    JSON_ARRAY('alt', 'title', 'description'),
    'alt'),
('HTML', 'Quelle balise est utilisée pour insérer une vidéo ?',
    JSON_ARRAY('<media>', '<video>', '<movie>'),
    '<video>');

-- =====================
-- Thématique : CSS
-- =====================
INSERT INTO Questions (thematique, question, options, correctAnswers) VALUES
('CSS', 'Que signifie CSS ?',
    JSON_ARRAY('Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style System'),
    'Cascading Style Sheets'),
('CSS', 'Quelle propriété définit la couleur du texte ?',
    JSON_ARRAY('color', 'text-color', 'font-color'),
    'color'),
('CSS', 'Quelle propriété change l’arrière-plan ?',
    JSON_ARRAY('background', 'background-color', 'bgcolor'),
    'background-color'),
('CSS', 'Quel sélecteur cible tous les paragraphes ?',
    JSON_ARRAY('p', '.p', '#p'),
    'p'),
('CSS', 'Quelle unité est relative à la taille de la police du parent ?',
    JSON_ARRAY('px', 'em', '%'),
    'em'),
('CSS', 'Quelle propriété définit la taille de la police ?',
    JSON_ARRAY('font-size', 'text-size', 'size'),
    'font-size'),
('CSS', 'Comment sélectionner un élément avec id="menu" ?',
    JSON_ARRAY('#menu', '.menu', 'menu'),
    '#menu'),
('CSS', 'Comment sélectionner tous les éléments avec class="item" ?',
    JSON_ARRAY('#item', '.item', 'item'),
    '.item'),
('CSS', 'Quelle propriété permet de changer la largeur d’un élément ?',
    JSON_ARRAY('height', 'size', 'width'),
    'width'),
('CSS', 'Quelle valeur de position permet de fixer un élément ?',
    JSON_ARRAY('absolute', 'relative', 'fixed'),
    'fixed');

-- =====================
-- Thématique : JavaScript
-- =====================
INSERT INTO Questions (thematique, question, options, correctAnswers) VALUES
('JavaScript', 'Que signifie JS ?',
    JSON_ARRAY('JavaSource', 'JavaScript', 'JustScript'),
    'JavaScript'),
('JavaScript', 'Comment déclare-t-on une variable ?',
    JSON_ARRAY('var x;', 'variable x;', 'v x;'),
    'var x;'),
('JavaScript', 'Quelle méthode affiche un message dans la console ?',
    JSON_ARRAY('print()', 'console.log()', 'alert()'),
    'console.log()'),
('JavaScript', 'Quel opérateur compare en valeur et type ?',
    JSON_ARRAY('==', '===', '='),
    '==='),
('JavaScript', 'Quelle méthode convertit une chaîne en entier ?',
    JSON_ARRAY('parseInt()', 'Number()', 'toInt()'),
    'parseInt()'),
('JavaScript', 'Quel mot-clé définit une constante ?',
    JSON_ARRAY('let', 'var', 'const'),
    'const'),
('JavaScript', 'Comment écrire une fonction nommée "test" ?',
    JSON_ARRAY('function test() {}', 'func test() {}', 'def test() {}'),
    'function test() {}'),
('JavaScript', 'Quel objet représente le document HTML ?',
    JSON_ARRAY('window', 'document', 'DOM'),
    'document'),
('JavaScript', 'Quelle fonction arrête l’exécution pendant un certain temps ?',
    JSON_ARRAY('setTimeout()', 'setInterval()', 'pause()'),
    'setTimeout()'),
('JavaScript', 'Quelle boucle parcourt un tableau ?',
    JSON_ARRAY('for', 'foreach', 'for...of'),
    'for...of');
