USE quiz;

INSERT INTO Questions (thematique, question, options, correctAnswers) VALUES
('HTML', 'Que signifie HTML ?',
    JSON_ARRAY('HyperText Markup Language', 'Hyperlinks and Text Markup Language', 'Home Tool Markup Language'),
    JSON_ARRAY('HyperText Markup Language')),
('HTML', 'Quel est l’élément racine d’un document HTML ?',
    JSON_ARRAY('<html>', '<head>', '<body>'),
    JSON_ARRAY('<html>')),
('HTML', 'Quel tag est utilisé pour insérer une image ?',
    JSON_ARRAY('<img>', '<image>', '<pic>'),
    JSON_ARRAY('<img>')),
('HTML', 'Quelle balise définit un lien hypertexte ?',
    JSON_ARRAY('<link>', '<a>', '<href>'),
    JSON_ARRAY('<a>')),
('HTML', 'Quelle balise est utilisée pour les titres principaux ?',
    JSON_ARRAY('<title>', '<h1>', '<heading>'),
    JSON_ARRAY('<h1>')),
('HTML', 'Quel attribut d’un lien définit l’URL de destination ?',
    JSON_ARRAY('src', 'href', 'link'),
    JSON_ARRAY('href')),
('HTML', 'Quelle balise définit une liste ordonnée ?',
    JSON_ARRAY('<ul>', '<ol>', '<li>'),
    JSON_ARRAY('<ol>')),
('HTML', 'Quelle balise est utilisée pour créer un tableau ?',
    JSON_ARRAY('<table>', '<tab>', '<grid>'),
    JSON_ARRAY('<table>')),
('HTML', 'Quel attribut d’une image définit le texte alternatif ?',
    JSON_ARRAY('alt', 'title', 'description'),
    JSON_ARRAY('alt')),
('HTML', 'Quelle balise est utilisée pour insérer une vidéo ?',
    JSON_ARRAY('<media>', '<video>', '<movie>'),
    JSON_ARRAY('<video>'));

-- =====================
-- Thématique : CSS
-- =====================
INSERT INTO Questions (thematique, question, options, correctAnswers) VALUES
('CSS', 'Que signifie CSS ?',
    JSON_ARRAY('Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style System'),
    JSON_ARRAY('Cascading Style Sheets')),
('CSS', 'Quelle propriété définit la couleur du texte ?',
    JSON_ARRAY('color', 'text-color', 'font-color'),
    JSON_ARRAY('color')),
('CSS', 'Quelle propriété change l’arrière-plan ?',
    JSON_ARRAY('background', 'background-color', 'bgcolor'),
    JSON_ARRAY('background-color')),
('CSS', 'Quel sélecteur cible tous les paragraphes ?',
    JSON_ARRAY('p', '.p', '#p'),
    JSON_ARRAY('p')),
('CSS', 'Quelle unité est relative à la taille de la police du parent ?',
    JSON_ARRAY('px', 'em', '%'),
    JSON_ARRAY('em')),
('CSS', 'Quelle propriété définit la taille de la police ?',
    JSON_ARRAY('font-size', 'text-size', 'size'),
    JSON_ARRAY('font-size')),
('CSS', 'Comment sélectionner un élément avec id="menu" ?',
    JSON_ARRAY('#menu', '.menu', 'menu'),
    JSON_ARRAY('#menu')),
('CSS', 'Comment sélectionner tous les éléments avec class="item" ?',
    JSON_ARRAY('#item', '.item', 'item'),
    JSON_ARRAY('.item')),
('CSS', 'Quelle propriété permet de changer la largeur d’un élément ?',
    JSON_ARRAY('height', 'size', 'width'),
    JSON_ARRAY('width')),
('CSS', 'Quelle valeur de position permet de fixer un élément ?',
    JSON_ARRAY('absolute', 'relative', 'fixed'),
    JSON_ARRAY('fixed'));

-- =====================
-- Thématique : JavaScript
-- =====================
INSERT INTO Questions (thematique, question, options, correctAnswers) VALUES
('JavaScript', 'Que signifie JS ?',
    JSON_ARRAY('JavaSource', 'JavaScript', 'JustScript'),
    JSON_ARRAY('JavaScript')),
('JavaScript', 'Comment déclare-t-on une variable ?',
    JSON_ARRAY('var x;', 'variable x;', 'v x;'),
    JSON_ARRAY('var x;')),
('JavaScript', 'Quelle méthode affiche un message dans la console ?',
    JSON_ARRAY('print()', 'console.log()', 'alert()'),
    JSON_ARRAY('console.log()')),
('JavaScript', 'Quel opérateur compare en valeur et type ?',
    JSON_ARRAY('==', '===', '='),
    JSON_ARRAY('===')),
('JavaScript', 'Quelle méthode convertit une chaîne en entier ?',
    JSON_ARRAY('parseInt()', 'Number()', 'toInt()'),
    JSON_ARRAY('parseInt()')),
('JavaScript', 'Quel mot-clé définit une constante ?',
    JSON_ARRAY('let', 'var', 'const'),
    JSON_ARRAY('const')),
('JavaScript', 'Comment écrire une fonction nommée "test" ?',
    JSON_ARRAY('function test() {}', 'func test() {}', 'def test() {}'),
    JSON_ARRAY('function test() {}')),
('JavaScript', 'Quel objet représente le document HTML ?',
    JSON_ARRAY('window', 'document', 'DOM'),
    JSON_ARRAY('document')),
('JavaScript', 'Quelle fonction arrête l’exécution pendant un certain temps ?',
    JSON_ARRAY('setTimeout()', 'setInterval()', 'pause()'),
    JSON_ARRAY('setTimeout()')),
('JavaScript', 'Quelle boucle parcourt un tableau ?',
    JSON_ARRAY('for', 'foreach', 'for...of'),
    JSON_ARRAY('for...of'));
